### ISSUE TITLE
DataPreprocesser(.) in datacollector.ipynb?

### ISSUE THREAD

**Issue by RushiBhatt007** [NathanMalta/VRImitationLearning#1]
Can you please share the DataPreprocesser(.) function being used in datacollector.ipynb?

Thanks in advance

**Comment by NathanMalta** [comment]
Hey, thanks for your interest in the project!

Looks like I made a typo in that notebook.  Just resolved in the latest commit (7bd1cd4).

Happy coding!
Nathan

**Comment by RushiBhatt007** [comment]
Thanks for the quick update. It works fine for me!

Best,
Rushi
